sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: 123456
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPe
    access-key-secret: U6k1brOz8
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    auth: 123456
    database: 10
  wechat:
    appid: wx546f9cca9ec25dda
    secret: 0d457c612f67617a4193a8ee541c6205
